#!/bin/bash
# first arg: path/to/occurences
# second arg: path/to/coverage
# eg. nsync-fs/script/adapter_diff learn-ide-tree/lib/* nsync-fs/src/adapters/*

grep -ohr "fs\.\w*[(| ]" $1 | sed 's/^fs\.\(.*\).$/\1/' | sort -u > fs_occurences
grep -ohr "shell\.\w*[(| ]" $1 | sed 's/^shell\.\(.*\).$/\1/' | sort -u > shell_occurences
cat fs_occurences shell_occurences | sort -u > occurences
grep -ohr "\w*: [(|-]" $2 | sed 's/.\{3\}$//' | grep -v "constructor" | sort -u > coverage

echo "Diff of adapter usage vs coverage:"
diff occurences coverage
rm fs_occurences shell_occurences occurences coverage

echo "fs-plus references:"
ag 'fs-plus' $1

